# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: hardwarehacklab.github.io
url: 'hardwarehacklab.github.io'
author:
  name: Andrew McWilliams
  email: andy@jahya.net

# Grunt handles images and assets.
exclude: ['images', 'stylesheets', 'javascript', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true
excerpt_separator: <!--excerpt-ends-->

permalink: /stories/:title/
paginate: 7
paginate_path: "/stories/page:num/"

# Markdown library
markdown: kramdown
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   use_coderay: false
#   coderay:
#     coderay_wrap: div
#     coderay_line_numbers: inline
#     coderay_line_numbers_start: 1
#     coderay_tab_width: 4
#     coderay_bold_every: 10
#     coderay_css: style

highlighter: true
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  
collections:
  members:
    output: true
    permalink: /members/:title/
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  - 
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      bodyid: "stories"
      bodyclass: "content article"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      bodyid: "projects"
      bodyclass: "content article"
